# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b37936aa07181a0f1b0ac5d5c16189f86284f7cf4f09503df959ae6f4a01e28bfbca870f03f742da546cfc17007ffb4466a5c50a18bad3cd960e6df72fdb01

test:
  secret_key_base: 02a83357cfc63dcf9832529e20bb7551ac91fb56a2b8e63d0a15121dc1543ec6ed19e385b96a11201e3e067f09e63266f50dc983fac97b47abf68c97ecd4bdde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
